const loveMessages = [
    "I love you more than words can say.",
    "You are my sunshine on a rainy day.",
    "With you, every moment is magical.",
    "My heart belongs to you.",
    "You are the love of my life.",
    "I am grateful for every moment with you.",
    "Your smile is my favorite thing in the world.",
    "Together, we make the perfect team.",
    "You are the source of my joy, the center of my world, and the whole of my heart.",
    "When I say I love you more, I don't mean I love you more than you love me",
    "I saw that you were perfect, and so I loved you.",
    "You have bewitched me, body and soul, and I love, I love, I love you.",
    "To the world, you may be one person, but to one person you are the world.",
    "Love is not about how many days, months, or years you have been together. Love is about how much you love each other every single day.",
    "I look at you and see the rest of my life in front of my eyes.",
    "I swear I couldn't love you more than I do right now, and yet I know I will tomorrow.",
    "My love for you is past the mind, beyond my heart, and into my soul",
    "I have loved you all my life; it has just taken me this long to find you",
    "I would rather spend one lifetime with you than face all the ages of this world alone.",
    "In you, I've found the love of my life and my closest, truest friend.",
    "I love you more than there are stars in the sky and fish in the sea.",
    "Every love story is beautiful, but ours is my favorite.",
    "You are my today and all of my tomorrows.",
    "I love you as certain dark things are to be loved, in secret, between the shadow and the soul.",
    "I love you more than coffee, but please don't make me prove it.",
    "Love her but leave her wild." - "Love Her Wild: Poems",
    "You are my sun, my moon, and all my stars.",
    "Love is a single soul inhabiting two bodies.",
    "I am yours, don't give myself back to me.",
    "You have me. Until every last star in the galaxy dies. You have me.",
    "Your voice is my favorite sound.",
    "So, I love you because the entire universe conspired to help me find you.",
    "I love you and that's the beginning and end of everything.",
    "You are my heart, my life, my one and only thought.",
    "To love is nothing. To be loved is something. But to love and be loved, that’s everything.",
    "I love you not only for what you are but for what I am when I am with you.",
    "In you, I have found the love of my life and my closest, truest friend.",
    "I could start fires with what I feel for you.",
    "You are every reason, every hope, and every dream I've ever had.",
    "If I had a flower for every time I thought of you, I could walk in my garden forever.",
    "For it was not into my ear you whispered, but into my heart. It was not my lips you kissed, but my soul.",
    "I wish I could turn back the clock. I’d find you sooner and love you longer",
    "Your love shines in my heart as the sun that shines upon the earth.",
    "Each day I love you more, today more than yesterday and less than tomorrow.",
    "Whatever our souls are made of, his and mine are the same.",
    "I love you for all that you are, all that you have been, and all you're yet to be.",
    "You are the finest, loveliest, tenderest, and most beautiful person I have ever known—and even that is an understatement.",
    "I could watch you for a single minute and find a thousand things that I love about you.",
    "Loving you was never an option. It was a necessity.",
    "Every time I see you, I fall in love all over again.",
    "Love is composed of a single soul inhabiting two bodies.",
    "I love you more than I have ever found a way to say to you.",
    "You are my blue crayon, the one I never have enough of, the one I use to color my sky.",
    "Whenever I'm alone with you, you make me feel like I am home again.",
    "You are the source of my joy, the center of my world, and the whole of my heart.",
    "When I say I love you more, I don't mean I love you more than you love me. I mean I love you more than the bad days ahead of us, I love you more than any fight we will ever have. I love you more than the distance between us, I love you more than any obstacle that could try and come between us. I love you the most.",
    "I saw that you were perfect, and so I loved you. Then I saw that you were not perfect and I loved you even more",
    "I love you and I don't want to lose you. Because my life has been better since the day I found out.",
    "If I know what love is, it is because of you.",
    "I love you more than any obstacle that might get in our way.",
    "I love you more than words can show, I think about you more than you could ever know, until forever this will be true because there is no one I would ever love the way I love you.",
    "You are my paradise and I would happily get stranded on you for a lifetime",
    "I've fallen in love many times… but always with you.",
    "I love you more than yesterday, less than tomorrow.",
    "I love you without knowing how, or when, or from where. I love you simply, without problems or pride: I love you in this way because I do not know any other way of loving but this, in which there is no I or you, so intimate that your hand upon my chest is my hand, so intimate that when I fall asleep your eyes close.",
    "I seem to have loved you in numberless forms, numberless times, in life after life, in age after age forever.",
    "I have waited for this opportunity for more than half a century, to repeat to you once again my vow of eternal fidelity and everlasting love.",
    "When I look at you and I'm listening to you, I know that I'm home.",
    "It's like my life isn't even real to me unless you're there and you're in it and I'm sharing it with you",
    "If I had to choose between breathing and loving you, I would use my last breath to tell you I love you.",
    "You are the last thought in my mind before I drift off to sleep and the first thought when I wake up each morning.",
    "Being deeply loved by someone gives you strength while loving someone deeply gives you courage.",
    "I choose you. And I'll choose you over and over and over. Without pause, without a doubt, in a heartbeat. I'll keep choosing you",
    "You don't love someone for their looks, or their clothes, or for their fancy car, but because they sing a song only you can hear.",
    "I have found the one whom my soul loves",
    "In your smile, I see something more beautiful than the stars.",
    "You are the poem I never knew how to write, and this life is the story I have always wanted to tell",
    "To me, you are perfect.",
    "You have a place in my heart no one else could have.",
    "If you remember me, then I don't care if everyone else forgets.",
    "I choose you. Over and over again, without pause, without a doubt, in a heartbeat. I'll keep choosing you.",
    "You are my today and all my tomorrows.",
    "I saw that you were imperfect yet perfect, and fell in love.",
    "You're my person. You will always be my person.",
    "I love you like a fat kid loves cake.You are the peanut to my butter, the star to my burst, the pop to my tart, the fruit to my loop, the milk to my cookie, the ice to my cream, the ketchup to my fries, the key to my heart.",
    "I could stay awake just to hear you breathing, watch you smile while you are sleeping, while you’re far away and dreaming.",
    "You make me happier than I ever thought I could be and if you let me, I will spend the rest of my life trying to make you feel the same way.",
    "If you live to be a hundred, I want to live to be a hundred minus one day, so I never have to live without you",
    "I've realized that the Beatles got it wrong. Love isn't all we need—love is all there is.",
    "I want to be the reason behind your smile because surely you are the reason behind mine.",
    "I fell in love the way you fall asleep: slowly, and then all at once",
    "I love you as the plant that never blooms but carries in itself the light of hidden flowers; thanks to your love a certain solid fragrance, risen from the earth, lives darkly in my body.",
    "I love you more than I could ever promise because you take me the way I am.",
    "You are my best friend, my human diary, and my other half. You mean the world to me and I love you.",
    "If I had a flower for every time I thought of you... I could walk through my garden forever.",
    "Your love is all I need to feel complete.",
    "Being with you is like having every single one of my wishes come true",
    "You must be made of stardust because every little thing you do is magical.",
    "My heart is and always will be yours.",
    "Your absence has gone through me like thread through a needle. Everything I do is stitched with its color",
    "I love you, and I will love you until I die, and if there's a life after that, I'll love you then.",
];

const flowers = [
    { name: "Rose", image: "images/rose3.jpg" },
    { name: "Tulip", image: "images/tulip.jpg" },
    { name: "Sunflower", image: "images/sunflower.jpg" },
    { name: "Daisy", image: "images/daisy.webp" },
    { name: "Lily", image: "images/lily-flower.jpg" },
    { name: "Blue-Orchid", image: "images/blue-orchids.jpg" },
    { name: "Cherry Blossom", image: "images/cherry-blossom.webp"},
    { name:"Daffodil", image: "images/daffodil.webp"},
    { name: "Poppy", image: "images/poppy.webp"},
    { name: "Bluebell", image: "images/bluebell.jpg"},
    { name: "Crocus", image: "images/crocus.jpg"},
    { name: "Water Lily", image: "images/water-lily.jpeg"},
    { name: "Forget Me Not", image: "images/forget-me-not.webp"},
    { name: "Aster", image: "images/aster.jpeg"},
    { name: "Snowdrop", image: "images/snowdrop.webp"},
    { name: "Violet", image: "images/violet.webp"},
    { name: "Peony", image: "images/peony.webp"},
    { name: "Bird Of Paradise", image: "images/bird-of-paradise.jpg"},
    { name: "Dandelion", image: "images/dandelion.jpg"},
    { name: "Iris", image: "images/iris.avif"},
    { name: "Ixora", image: "images/ixora.webp"},
    { name: "Tiger Lily", image: "images/tiger-lily.webp"},
    { name: "Dahlia", image: "images/dahlia.jpg"},
    { name: "Lavender", image: "images/lavender.webp"},
    { name: "Canna", image: "images/canna.webp"},
    { name: "Cockspur", image: "images/cockspur.jpg"},
    { name: "Cockscomb", image: "images/cockscomb.webp"},
    { name: "Lilac", image: "images/lilac.avif"},
    { name: "Lotus", image: "images/lotus.webp"},
    { name: "Allium", image: "images/allium.webp"},
    { name: "Allysum", image: "images/alyssum.jpg"},
    { name: "Anemone", image: "images/anemone.jpeg"},
    { name: "Arabian Jasmine", image: "images/arabian-jasmine.webp"},
    { name: "Artemisia", image: "images/ARTEMISIA.webp"},
    { name: "Astilbe", image: "images/astilbe.jpg"},
    { name: "Bachelor Button", image: "images/bachelor-button.jpg"},
    { name: "Balloon Flowers", image: "images/balloon.jpg"},
    { name: "Bee Balm", image: "images/bee-balm.jpg"},
    { name: "Bell Flower", image: "images/bell.jpg"},
    { name: "Blanket Flower", image: "images/blanklet.jpg"},
    { name: "Bleeding Heart", image: "images/bleed.jpg"},
    { name: "Blue Water Lily", image: "images/blue-water.jpg"},
    { name: "Bougainvillea", image: "images/boug.webp"},
    { name: "Broom Flowers", image: "images/broom.jpg"},
    { name: "Buttercups", image: "images/buttercups.webp"},
    { name: "Butterfly Bush", image: "images/butterfly.jpeg"},
    { name: "Butterfly Weed", image: "images/butterfly-weed.jpg"},
    { name: "Calendula", image: "images/calendula.webp"},
    { name: "Camellia", image: "images/camellia.jpg"},
    { name: "Cannabis(Bangi)", image: "images/cannabis.jpg"},
    { name: "Catmint", image: "images/catmint.webp"},
    { name: "China Rose", image: "images/china.webp"},
    { name: "Chrysanthemum", image: "images/chris.jpg"},
    { name: "Clematis", image: "images/clematis.jpg"},
    { name: "Cobra Saffron", image: "images/cobra.jpg"},
    { name: "Columbine", image: "images/columbine.jpg"},
    { name: "Cone Flower", image: "images/cone.jpg"},
    { name: "Coral Bells", image: "images/coral.jpg"},
    { name: "Coreopsis", image: "images/core.jpg"},
    { name: "Cosmos", image: "images/cosmos.webp"},
    { name: "Cyclamen", image: "images/cycl.webp"},
    { name: "Datura", image: "images/datura.jpg"},
    { name: "Day Lily", image: "images/day.jpg"},
    { name: "Delphinium", image: "images/delph.jpg"},
    { name: "Foxglove", image: "images/fox.jpg"},
    { name: "Gas Plant", image: "images/gas.webp"},
    { name: "Gayfeather", image: "images/gay.webp"},
    { name: "Geranium", image: "images/geranium.webp"},
    { name: "Gladiolus", image: "images/gladi.webp"},
    { name: "Globe Flower", image: "images/globe.jpg"},
    { name: "Golden Champa", image: "images/gold.jpeg"},
    { name: "Dianthus", image: "images/dianthus.jpg"},
    { name: "Digitalis", image: "images/digital.jpg"},
    { name: "Dragon", image: "images/dragon.jpg"},
    { name: "Flax", image: "images/flax.jpg"},
    { name: "Fleabane", image: "images/flea.jpg"},
    { name: "False Spirea", image: "images/false.webp"},
    { name: "Dusty Miller", image: "images/dusty-miller.jpg"},
    { name: "Eucalyptus", image: "images/eucalyptus.webp"},
    { name: "Dryopteris", image: "images/dryo.webp"},
    { name: "Pretty Like You", image: "images/pretty.jpg"},
    { name: "Lily of the Valley", image: "images/lily-of.jpg"},
    { name: "Poppy", image: "images/popp.jpg"},
    { name: "Plumbago", image: "images/plumbago.jpg"},
    { name: "Cosmos", image: "images/cosmos2.jpg"},
    { name: "Aster", image: "images/aster2.jpg"},
    { name: "Sweet Asylum", image: "images/sweet.jpg"},
    { name: "Hydrangea", image: "images/hydra.jpg"},
    { name: "Echincea", image: "images/echi.jpg"},
    { name: "Calibrachoa", image: "images/calibra.jpg"},
    { name: "Geranium", image: "images/gera.jpg"},
    { name: "Snapdragon", image: "images/snap.jpg"},
    { name: "Salvia", image: "images/salvia.jpg"},
    { name: "Lantana", image: "images/lan.jpg"},
    { name: "Gaura", image: "images/gaura.jpg"},
    { name: "Hibiscus", image: "images/hibis.jpg"},
    { name: "Impatiens", image: "images/imp.jpg"},
    { name: "Rudbeckia", image: "images/rud.jpg"},
    { name: "Passion Flower", image: "images/passion.jpg"},
    { name: "Petunias", image: "images/petunias.jpg"},
    { name: "Clematis", image: "images/clema.jpg"}
];

function getRandomItem(array) {
    return array[Math.floor(Math.random() * array.length)];
}

function generateMessage() {
    const randomMessage = getRandomItem(loveMessages);
    const randomFlower = getRandomItem(flowers);

    document.getElementById("loveMessage").textContent = randomMessage;
    document.getElementById("flowerImage").src = randomFlower.image;
    document.getElementById("flowerName").textContent = randomFlower.name;
}

// Generate an initial message and flower when the page loads
window.onload = generateMessage;
